["usr/local/bin/jq"]
type = "file"
executable = true
url = "https://github.com/stedolan/jq/releases/latest/download/jq-linux64"

["usr/local/bin/"]
type = "archive"
executable = true
url = "https://github.com/gnprice/toml-cli/releases/download/v0.2.3/toml-0.2.3-x86_64-linux.tar.gz"
stripComponents = 1
include = ["*/toml"]

["usr/local/bin/semver"]
type = "file"
executable = true
url =  "https://raw.githubusercontent.com/fsaintjacques/semver-tool/3.4.0/src/semver"
